/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IVoucher } from "../IVoucher";

export class IVoucher__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IVoucher {
    return new Contract(address, _abi, signerOrProvider) as IVoucher;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "uint64",
        name: "term_",
        type: "uint64",
      },
      {
        internalType: "uint256",
        name: "amount_",
        type: "uint256",
      },
      {
        internalType: "uint64[]",
        name: "maturities_",
        type: "uint64[]",
      },
      {
        internalType: "uint32[]",
        name: "percentages_",
        type: "uint32[]",
      },
      {
        internalType: "string",
        name: "originalInvestor_",
        type: "string",
      },
    ],
    name: "mint",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];
