/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IVoucher } from "./IVoucher";
export type { MiningVoucherDemo } from "./MiningVoucherDemo";

export { IVoucher__factory } from "./factories/IVoucher__factory";
export { MiningVoucherDemo__factory } from "./factories/MiningVoucherDemo__factory";
