/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface IVoucherInterface extends ethers.utils.Interface {
  functions: {
    "mint(uint64,uint256,uint64[],uint32[],string)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "mint",
    values: [BigNumberish, BigNumberish, BigNumberish[], BigNumberish[], string]
  ): string;

  decodeFunctionResult(functionFragment: "mint", data: BytesLike): Result;

  events: {};
}

export class IVoucher extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IVoucherInterface;

  functions: {
    mint(
      term_: BigNumberish,
      amount_: BigNumberish,
      maturities_: BigNumberish[],
      percentages_: BigNumberish[],
      originalInvestor_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "mint(uint64,uint256,uint64[],uint32[],string)"(
      term_: BigNumberish,
      amount_: BigNumberish,
      maturities_: BigNumberish[],
      percentages_: BigNumberish[],
      originalInvestor_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  mint(
    term_: BigNumberish,
    amount_: BigNumberish,
    maturities_: BigNumberish[],
    percentages_: BigNumberish[],
    originalInvestor_: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "mint(uint64,uint256,uint64[],uint32[],string)"(
    term_: BigNumberish,
    amount_: BigNumberish,
    maturities_: BigNumberish[],
    percentages_: BigNumberish[],
    originalInvestor_: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    mint(
      term_: BigNumberish,
      amount_: BigNumberish,
      maturities_: BigNumberish[],
      percentages_: BigNumberish[],
      originalInvestor_: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    "mint(uint64,uint256,uint64[],uint32[],string)"(
      term_: BigNumberish,
      amount_: BigNumberish,
      maturities_: BigNumberish[],
      percentages_: BigNumberish[],
      originalInvestor_: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;
  };

  filters: {};

  estimateGas: {
    mint(
      term_: BigNumberish,
      amount_: BigNumberish,
      maturities_: BigNumberish[],
      percentages_: BigNumberish[],
      originalInvestor_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "mint(uint64,uint256,uint64[],uint32[],string)"(
      term_: BigNumberish,
      amount_: BigNumberish,
      maturities_: BigNumberish[],
      percentages_: BigNumberish[],
      originalInvestor_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    mint(
      term_: BigNumberish,
      amount_: BigNumberish,
      maturities_: BigNumberish[],
      percentages_: BigNumberish[],
      originalInvestor_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "mint(uint64,uint256,uint64[],uint32[],string)"(
      term_: BigNumberish,
      amount_: BigNumberish,
      maturities_: BigNumberish[],
      percentages_: BigNumberish[],
      originalInvestor_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
